# Generated by Django 2.2.3 on 2019-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_pw2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.BooleanField()),
                ('birth', models.DateField()),
            ],
        ),
    ]
