# Generated by Django 2.2.3 on 2019-08-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_pw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_pw2',
        ),
    ]
