# Generated by Django 2.2.3 on 2019-08-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190804_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_rating',
        ),
    ]
